if(NOT DEFINED AWJ_SHADER_HEADER)
    message(FATAL_ERROR "AWJ_SHADER_HEADER is required.")
endif()

foreach(required_name IN ITEMS AWJ_LUMA_CSO AWJ_GMSD_CSO AWJ_DOWNSAMPLE_CSO AWJ_MS_SSIM_CSO)
    if(NOT DEFINED ${required_name})
        message(FATAL_ERROR "${required_name} is required.")
    endif()
endforeach()

file(WRITE "${AWJ_SHADER_HEADER}" "#pragma once\n\n")
file(APPEND "${AWJ_SHADER_HEADER}" "namespace awj::visual_metrics_gpu_shaders {\n\n")

function(awj_append_shader_array variable_name input_path)
    file(READ "${input_path}" shader_hex HEX)
    string(LENGTH "${shader_hex}" shader_hex_length)
    if(shader_hex_length EQUAL 0)
        message(FATAL_ERROR "Shader bytecode is empty: ${input_path}")
    endif()
    math(EXPR shader_last_offset "${shader_hex_length} - 2")
    file(APPEND "${AWJ_SHADER_HEADER}" "inline constexpr unsigned char ${variable_name}[] = {\n")
    set(line "  ")
    set(column_count 0)
    foreach(offset RANGE 0 ${shader_last_offset} 2)
        string(SUBSTRING "${shader_hex}" ${offset} 2 shader_byte)
        string(APPEND line "0x${shader_byte}, ")
        math(EXPR column_count "${column_count} + 1")
        if(column_count EQUAL 12)
            file(APPEND "${AWJ_SHADER_HEADER}" "${line}\n")
            set(line "  ")
            set(column_count 0)
        endif()
    endforeach()
    if(NOT line STREQUAL "  ")
        file(APPEND "${AWJ_SHADER_HEADER}" "${line}\n")
    endif()
    file(APPEND "${AWJ_SHADER_HEADER}" "};\n")
    file(APPEND "${AWJ_SHADER_HEADER}" "inline constexpr unsigned int ${variable_name}Size = sizeof(${variable_name});\n\n")
endfunction()

awj_append_shader_array(kLumaShaderBytecode "${AWJ_LUMA_CSO}")
awj_append_shader_array(kGmsdShaderBytecode "${AWJ_GMSD_CSO}")
awj_append_shader_array(kDownsampleShaderBytecode "${AWJ_DOWNSAMPLE_CSO}")
awj_append_shader_array(kMsSsimShaderBytecode "${AWJ_MS_SSIM_CSO}")

file(APPEND "${AWJ_SHADER_HEADER}" "}  // namespace awj::visual_metrics_gpu_shaders\n")
